name: Build and deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Needed by dorny/test-reporter@v1
permissions:
  statuses: write
  checks: write

env:
  AZURE_WEBAPP_PACKAGE_PATH: src/Server/publish
  AZURE_WEBAPP_NAME: jordnaer
  WORKING_DIRECTORY: src/Server
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true
          
      - name: Restore Nugets
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration Release --no-restore

      - name: Test
        run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: xUnit Tests
          path: "**.trx"
          reporter: dotnet-trx

      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" -c Release --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Deploy to Azure App Service
        id: deploy-to-azure-app-service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
