name: Build and deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-restore --no-build

      - name: Publish
        run: dotnet publish --no-restore --no-build -c Release

      - name: Deploy to Azure App Service
        id: deploy-to-azure-app-service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Jordnær'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
