name: Website - Deploy

on:
  push:
    tags:
      - "release-website-v*.*.*"
  workflow_dispatch:

# Needed by dorny/test-reporter@v1
permissions:
  statuses: write
  checks: write

env:
  AZURE_WEBAPP_PACKAGE_PATH: src/web/Server/publish
  TESTS_DIRECTORY: tests/web/Jordnaer.Server.Tests
  AZURE_WEBAPP_NAME: jordnaer
  WORKING_DIRECTORY: src/web/Server
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Restore Nugets
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration Release --no-restore

      - name: Test
        run: dotnet test "${{ env.TESTS_DIRECTORY }}" --logger "trx;LogFileName=test-results.trx" --filter Category!=ManualTest
        env:
          ConnectionStrings__AppConfig: ${{ secrets.AZURE_APP_CONFIGURATION_CONNECTION_STRING }}

      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" -c Release --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
