name: Website Backend - Run Tests

on:
  push:
    paths:
      - "src/web/**"
      - "tests/web/Jordnaer.Tests/**"
      - ".github/workflows/website_backend_ci.yml"
  workflow_dispatch:

env:
  WORKING_DIRECTORY: tests/web/Jordnaer.Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Test
        # Dependabot cannot access secrets, so we disable this step for Dependabot
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        run: >
          dotnet test "${{ env.WORKING_DIRECTORY }}" 
          --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true" 
          --filter Category!=ManualTest
        env:
          ConnectionStrings__AppConfig: ${{ secrets.AZURE_APP_CONFIGURATION_CONNECTION_STRING }}
