name: Website - Deploy

on:
  push:
    tags:
      - "release-website-v*.*.*"
  workflow_dispatch:

# Needed by dorny/test-reporter@v1
permissions:
  statuses: write
  checks: write

env:
  AZURE_WEBAPP_PACKAGE_PATH: src/web/Server/publish
  TESTS_DIRECTORY: tests/web/Jordnaer.Server.Tests
  AZURE_WEBAPP_NAME: jordnaer
  WORKING_DIRECTORY: src/web/Server
  MSSQL_SA_PASSWORD: 6efe173b-3e33-4d6c-8f50-3e5f7cadd54c
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "${{ env.MSSQL_SA_PASSWORD }}"
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore Nugets
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration Release --no-restore
          
      - name: Test
        run: dotnet test "${{ env.TESTS_DIRECTORY }}" --logger "trx;LogFileName=test-results.trx" --filter Category!=ManualTest
        env:
          ConnectionStrings__AppConfig: ${{ secrets.AZURE_APP_CONFIGURATION_CONNECTION_STRING }}
          ConnectionStrings__JordnaerDbContext: "Server=localhost,1433;Database=jordnaer;User ID=sa;Password=${{ env.MSSQL_SA_PASSWORD }};Persist Security Info=False;TrustServerCertificate=true;"
          
      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" -c Release --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
